### PR TITLE
Update release platforms.

### PR DESCRIPTION
**Pull request by cottsay**
Drop Ubuntu Xenial.
Add Ubuntu Jammy.
Add Debian Bullseye.

### CODE REVIEW

**Comment by Briancbn** [comment]
Lgtm, I will merge this after the `colcon-core` one is merged

**Review by Briancbn — APPROVED** [review]

**Comment by Briancbn** [comment]
@cottsay I can't seemed to release as jammy deb yet. `publish-python` packagecloud gem error when uploading.
```
jammy isn't a valid version of Ubuntu

If you don't see your OS or version here, send us an email at support@packagecloud.io:

        0. Ubuntu
        1. Debian
        2. LinuxMint
        3. Raspbian
        4. elementary OS

 0-4: 0
```
I will make the release after this is fixed.

@dirk-thomas Sorry about the mess in [packagecloud.io](https://packagecloud.io/dirk-thomas/colcon)

**Comment by cottsay** [comment]
@nuclearsandwich FYI

**Comment by nuclearsandwich** [comment]
That's unfortunate. I've contacted PackageCloud via email as suggested by the error message. Hopefully they'll get back to me soon.

**Comment by nuclearsandwich** [comment]
Ludicrously fast response from the PackageCloud support team. :love_letter:

:crossed_fingers: this means that we'll have Jammy up soon.

> Hi Steven, thanks for reaching out! Sorry for the inconvenience. I've flagged this issue and alerted our engineering team. They'll reach out when back online.
﻿
﻿-Luka

**Comment by Briancbn** [comment]
@nuclearsandwich  @cottsay Available now, I will make the release.

**Pull request merged**
